services:
  api:
    build: ./src
    ports:
      - "3000:3000"
    volumes:
      - ./:/
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    driver: bridge